// leave off @2x/@3x
const images = {
  logo: require('../Images/logo.png'),
  logoDark: require('../Images/logo.png'),
  clearLogo: require('../Images/logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/logo.png'),
  ignite: require('../Images/logo.png'),
  igniteClear: require('../Images/logo.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  stepsScale: require('../Images/assets/Steps_scale.png'),
  stepsOrange: require('../Images/assets/Steps_orange.png'),
  stepsOrangeActive: require('../Images/assets/Steps_orange_active.png'),
  stepsBlue: require('../Images/assets/Steps_blue.png'),
  stepsBlueActive: require('../Images/assets/Steps_blue_active.png'),
  stepsPurple: require('../Images/assets/Steps_purple.png'),
  stepsPurpleActive: require('../Images/assets/Steps_purple_active.png'),
  stepsGray: require('../Images/assets/Steps_gray.png'),
  checkboxNormal: require('../Images/assets/Checkbox_normal.png'),
  checkboxActive: require('../Images/assets/Checkbox_active.png'),
  playButtonMorning: require('../Images/assets/Play_btn_morning.png'),
  playButtonDay: require('../Images/assets/Play_btn_day.png'),
  playButtonNight: require('../Images/assets/Play_btn_night.png')
}

export default images
